/* Generated by re2c 0.13.5 on Tue May 12 13:02:10 2009 */
/**@file lexer.re
 *
 * @author Original author: Joseph D Poirier
 * @date   Creation date  : 16 August 2008
 *
 *
 * @version X.X.X
 *
 * VERSION    DATE/AUTHOR              COMMENT
 *            15Sept2007 Jpoirier         Added initial version information.
 *
 *
 * Copyright 2008 Joseph D Poirier. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer. Redistributions in binary
 * form must reproduce the above copyright notice, this list of conditions and
 * the following disclaimer in the documentation and/or other materials provided
 * with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE FREEBSD PROJECT ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
 * EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are
 * those of the authors and should not be interpreted as representing official
 * policies, either expressed or implied.
 */
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include "xvm.h"
#include "xvm_inner.h"
#include "lexer.h"
#include "directives.h"
#include "compiler.h"
#include "voc.h"
#include "code.h"
#include "files.h"
#include "macro.h"
#include "variable.h"
#include "ffi.h"


#define YYCTYPE         int8_t
#define YYCURSOR        str
#define YYLIMIT         str + cnt
#define YYMARKER        marker
/*#define YYCTXMARKER*/

#define YYFILL(n)

int32_t lexer(int8_t* str, int32_t cnt)
{
    /* Obviously this makes the system non-reentrant */
#if HAVE_FFI
    static int32_t  ffi_lib_state   = NOT_OK_TO_IMPORT_FUNC;
#endif
    static int32_t  prev_state      = OK_TO_COMPILE;
    static int32_t  curr_state      = OK_TO_COMPILE;
    static bool     add_word        = false;
#if HAVE_PRINTF
    int32_t         tmp             = 0;
#endif
    int8_t*         str_start       = 0;
    int8_t*         marker          = 0;

    if(curr_state == BLK_CMT)
        goto c_blk_comment;

    if(curr_state != WORD_DEF && curr_state != IMPORT_FUNCTION)
    {
//        printf("\n OK_TO_COMPILE \n");
        curr_state = OK_TO_COMPILE;
    }

    for(;;)
    {

/*
    \0  : Null character
    \a  : Bell
    \b  : Backspace
    \t  : Horizontal tab
    \n  : Kine feed
    \v  : Vertical tab
    \f  : Form feed
    \r  : Carriage return
    \e  : Escape

    Note that some of the rules may use identifiers in their raw form, e.g.,
    you may see a newline in the form "\n" used rather than its token definition
    "NEWLINE" emdedded in a rule. That's because in most cases token definitions
    have an action associated with it, as defined within the parenthesis, that
    would be undesirable for the current process.

    Internal state, which is returned to the caller. Obviously this makes
    the system non-reentrant and not thread safe - you've been warned.
    ------------------------------------------------------------------------
    BYE                 (-1)
    WORD_DEF            (-2)
    BLK_CMT             (-3)
    LINE_CMT            (-4)
    LINE_CMT_END        (-5)
    OK_TO_COMPILE       (-6)
    PRINTED_HELP        (-7)
    ERROR_OCCURED       (-8)

    Items that can change the internal state:
        - the initial entry in to the lexer function
        - the start of comment
        - the end of comment
        - the start of word definition
        - the end of word definition


    We assume the print directives are used within a wrod definition, i.e.
    the value or string is compiled.
*/

/*
     Save the current pointer address. This will hold the start
     address of a token (when one is found), 'str - 1' is the
     end address of the token string.
*/
    str_start = str;
//printf("str_start: %s\n", str_start);




{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		/* table 1 .. 8: 0 */
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 33,   1,  40,   0,   1,   1,   1,   0, 
		  0,   0,   1,   0,   0,   1,   1,   1, 
		199, 199, 195, 195, 195, 195, 195, 195, 
		131, 131,   1,   0,   0,   0,   0,   0, 
		  1, 145, 145, 145, 145, 145, 145,  17, 
		 17,  17,  17,  17,  17,  17,  17,  17, 
		 17,  17,  17,  17,  17,  17,  17,  17, 
		 17,  17,  17,   1,   0,   0,   1,  16, 
		  1, 145, 145, 145, 145, 145, 145,  17, 
		 17,  17,  17,  17,  17,  17,  17,  17, 
		 17,  17,  17,  17,  17,  17,  17,  17, 
		 17,  17,  17,   1,   0,   1,   1,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		/* table 9 .. 13: 256 */
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,  88,  88,  88,  88,  88,  88,  88, 
		120, 136,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  64,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,  88, 
		 88,  88,  88,  88,  88,  88,  88,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};

	if ((YYLIMIT - YYCURSOR) < 10) YYFILL(10);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x07:
	case 0x08:
	case '\t':
	case '\v':
	case '\f':
	case '\r':
	case ' ':	goto yy5;
	case '\n':	goto yy3;
	case '!':	goto yy57;
	case '"':
	case '$':
	case '%':
	case '&':
	case '\'':
	case ')':
	case ',':
	case '?':
	case 'G':
	case 'K':
	case 'Q':
	case 'Y':
	case 'Z':
	case '[':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'g':
	case 'k':
	case 'q':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy68;
	case '#':	goto yy37;
	case '(':	goto yy67;
	case '*':	goto yy63;
	case '+':	goto yy46;
	case '-':	goto yy47;
	case '.':	goto yy50;
	case '/':	goto yy7;
	case '0':	goto yy44;
	case '1':	goto yy45;
	case '2':	goto yy48;
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy49;
	case ':':	goto yy27;
	case ';':	goto yy28;
	case '<':	goto yy62;
	case '=':	goto yy66;
	case '>':	goto yy55;
	case '@':	goto yy56;
	case 'A':	goto yy58;
	case 'B':	goto yy17;
	case 'C':	goto yy38;
	case 'D':	goto yy21;
	case 'E':	goto yy13;
	case 'F':	goto yy35;
	case 'H':	goto yy9;
	case 'I':	goto yy11;
	case 'J':	goto yy25;
	case 'L':	goto yy23;
	case 'M':	goto yy64;
	case 'N':	goto yy40;
	case 'O':	goto yy53;
	case 'P':	goto yy51;
	case 'R':	goto yy33;
	case 'S':	goto yy42;
	case 'T':	goto yy15;
	case 'U':	goto yy19;
	case 'V':	goto yy31;
	case 'W':	goto yy29;
	case 'X':	goto yy60;
	case '\\':	goto yy8;
	case 'a':	goto yy59;
	case 'b':	goto yy18;
	case 'c':	goto yy39;
	case 'd':	goto yy22;
	case 'e':	goto yy14;
	case 'f':	goto yy36;
	case 'h':	goto yy10;
	case 'i':	goto yy12;
	case 'j':	goto yy26;
	case 'l':	goto yy24;
	case 'm':	goto yy65;
	case 'n':	goto yy41;
	case 'o':	goto yy54;
	case 'p':	goto yy52;
	case 'r':	goto yy34;
	case 's':	goto yy43;
	case 't':	goto yy16;
	case 'u':	goto yy20;
	case 'v':	goto yy32;
	case 'w':	goto yy30;
	case 'x':	goto yy61;
	default:	goto yy2;
	}
yy2:
	YYCURSOR = YYMARKER;
	if (yyaccept <= 3) {
		if (yyaccept <= 1) {
			if (yyaccept <= 0) {
				goto yy71;
			} else {
				goto yy82;
			}
		} else {
			if (yyaccept <= 2) {
				goto yy223;
			} else {
				goto yy227;
			}
		}
	} else {
		if (yyaccept <= 5) {
			if (yyaccept <= 4) {
				goto yy237;
			} else {
				goto yy335;
			}
		} else {
			goto yy931;
		}
	}
yy3:
	++YYCURSOR;
	{
                                                if(curr_state == VAR_DEF_VAL)
                                                    curr_state = VAR_DEF_END;
                                                break;
                                            }
yy5:
	++YYCURSOR;
	{ str += 1; continue; }
yy7:
	yych = *++YYCURSOR;
	if (yych <= '.') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy69;
			goto yy927;
		} else {
			if (yych == '*') goto yy929;
			goto yy69;
		}
	} else {
		if (yych <= 'M') {
			if (yych <= '/') goto yy930;
			if (yych <= 'L') goto yy69;
			goto yy932;
		} else {
			if (yych == 'm') goto yy933;
			goto yy69;
		}
	}
yy8:
	yych = *++YYCURSOR;
	if (yych == '\\') goto yy925;
	goto yy2;
yy9:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy912;
	goto yy69;
yy10:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy899;
	goto yy69;
yy11:
	yych = *++YYCURSOR;
	if (yych <= 'F') {
		if (yych == ' ') goto yy874;
		if (yych <= 'E') goto yy69;
		goto yy876;
	} else {
		if (yych <= 'L') goto yy69;
		if (yych <= 'M') goto yy877;
		if (yych <= 'N') goto yy878;
		goto yy69;
	}
yy12:
	yych = *++YYCURSOR;
	if (yych <= 'f') {
		if (yych == ' ') goto yy849;
		if (yych <= 'e') goto yy69;
		goto yy851;
	} else {
		if (yych <= 'l') goto yy69;
		if (yych <= 'm') goto yy852;
		if (yych <= 'n') goto yy853;
		goto yy69;
	}
yy13:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy844;
	goto yy69;
yy14:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy839;
	goto yy69;
yy15:
	yych = *++YYCURSOR;
	if (yych == 'H') goto yy829;
	if (yych == 'U') goto yy830;
	goto yy69;
yy16:
	yych = *++YYCURSOR;
	if (yych == 'h') goto yy819;
	if (yych == 'u') goto yy820;
	goto yy69;
yy17:
	yych = *++YYCURSOR;
	if (yych <= 'D') {
		if (yych == 'A') goto yy804;
		goto yy69;
	} else {
		if (yych <= 'E') goto yy805;
		if (yych == 'Y') goto yy806;
		goto yy69;
	}
yy18:
	yych = *++YYCURSOR;
	if (yych <= 'd') {
		if (yych == 'a') goto yy789;
		goto yy69;
	} else {
		if (yych <= 'e') goto yy790;
		if (yych == 'y') goto yy791;
		goto yy69;
	}
yy19:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy783;
	goto yy69;
yy20:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy777;
	goto yy69;
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':	goto yy750;
	case 'O':	goto yy751;
	case 'R':	goto yy752;
	case 'U':	goto yy753;
	default:	goto yy69;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy723;
	case 'o':	goto yy724;
	case 'r':	goto yy725;
	case 'u':	goto yy726;
	default:	goto yy69;
	}
yy23:
	yych = *++YYCURSOR;
	if (yych <= 'F') {
		if (yych <= 'D') goto yy69;
		if (yych <= 'E') goto yy709;
		goto yy710;
	} else {
		if (yych == 'O') goto yy711;
		goto yy69;
	}
yy24:
	yych = *++YYCURSOR;
	if (yych <= 'f') {
		if (yych <= 'd') goto yy69;
		if (yych <= 'e') goto yy695;
		goto yy696;
	} else {
		if (yych == 'o') goto yy697;
		goto yy69;
	}
yy25:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy693;
	goto yy69;
yy26:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy691;
	goto yy69;
yy27:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy689;
	goto yy69;
yy28:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy687;
	goto yy69;
yy29:
	yych = *++YYCURSOR;
	if (yych == 'O') goto yy681;
	goto yy69;
yy30:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy675;
	goto yy69;
yy31:
	yych = *++YYCURSOR;
	if (yych == 'A') goto yy663;
	goto yy69;
yy32:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy651;
	goto yy69;
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
	case '>':	goto yy619;
	case '@':	goto yy620;
	case 'E':	goto yy621;
	case 'O':	goto yy622;
	case 'P':	goto yy623;
	default:	goto yy69;
	}
yy34:
	yych = *++YYCURSOR;
	if (yych <= 'd') {
		if (yych <= '>') {
			if (yych <= '=') goto yy69;
			goto yy587;
		} else {
			if (yych == '@') goto yy588;
			goto yy69;
		}
	} else {
		if (yych <= 'n') {
			if (yych <= 'e') goto yy589;
			goto yy69;
		} else {
			if (yych <= 'o') goto yy590;
			if (yych <= 'p') goto yy591;
			goto yy69;
		}
	}
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case '*':	goto yy554;
	case '+':	goto yy555;
	case '-':	goto yy556;
	case '/':	goto yy557;
	case '1':	goto yy558;
	case 'I':	goto yy559;
	case 'L':	goto yy560;
	default:	goto yy69;
	}
yy36:
	yych = *++YYCURSOR;
	if (yych <= '/') {
		if (yych <= '+') {
			if (yych <= ')') goto yy69;
			if (yych <= '*') goto yy521;
			goto yy522;
		} else {
			if (yych == '-') goto yy523;
			if (yych <= '.') goto yy69;
			goto yy524;
		}
	} else {
		if (yych <= 'h') {
			if (yych == '1') goto yy525;
			goto yy69;
		} else {
			if (yych <= 'i') goto yy526;
			if (yych == 'l') goto yy527;
			goto yy69;
		}
	}
yy37:
	yych = *++YYCURSOR;
	if (yych <= 'I') {
		if (yych == 'D') goto yy487;
		if (yych <= 'H') goto yy69;
		goto yy488;
	} else {
		if (yych <= 'd') {
			if (yych <= 'c') goto yy69;
			goto yy489;
		} else {
			if (yych == 'i') goto yy490;
			goto yy69;
		}
	}
yy38:
	yych = *++YYCURSOR;
	if (yych == 'O') goto yy478;
	goto yy69;
yy39:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy469;
	goto yy69;
yy40:
	yych = *++YYCURSOR;
	if (yych <= 'H') {
		if (yych == 'E') goto yy437;
		goto yy69;
	} else {
		if (yych <= 'I') goto yy438;
		if (yych == 'O') goto yy439;
		goto yy69;
	}
yy41:
	yych = *++YYCURSOR;
	if (yych <= 'h') {
		if (yych == 'e') goto yy405;
		goto yy69;
	} else {
		if (yych <= 'i') goto yy406;
		if (yych == 'o') goto yy407;
		goto yy69;
	}
yy42:
	yych = *++YYCURSOR;
	if (yych <= 'S') {
		if (yych == 'P') goto yy381;
		goto yy69;
	} else {
		if (yych <= 'T') goto yy382;
		if (yych == 'W') goto yy383;
		goto yy69;
	}
yy43:
	yych = *++YYCURSOR;
	if (yych <= 's') {
		if (yych == 'p') goto yy357;
		goto yy69;
	} else {
		if (yych <= 't') goto yy358;
		if (yych == 'w') goto yy359;
		goto yy69;
	}
yy44:
	yych = *++YYCURSOR;
	if (yych <= '/') {
		if (yych <= '!') {
			if (yych == ' ') goto yy316;
			goto yy69;
		} else {
			if (yych <= '"') goto yy317;
			if (yych == '.') goto yy229;
			goto yy69;
		}
	} else {
		if (yych <= 'W') {
			if (yych <= '1') goto yy350;
			if (yych <= '7') goto yy352;
			if (yych <= '9') goto yy230;
			goto yy69;
		} else {
			if (yych <= 'X') goto yy354;
			if (yych == 'x') goto yy354;
			goto yy69;
		}
	}
yy45:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 4) {
		goto yy320;
	}
	switch (yych) {
	case ' ':	goto yy316;
	case '"':	goto yy317;
	case '+':	goto yy318;
	case '-':	goto yy319;
	case '.':	goto yy229;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy230;
	default:	goto yy69;
	}
yy46:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy314;
	if (yych <= '/') goto yy69;
	if (yych <= '9') goto yy49;
	goto yy69;
yy47:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy312;
	if (yych <= '/') goto yy69;
	if (yych <= '9') goto yy49;
	goto yy69;
yy48:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 2) {
		goto yy230;
	}
	if (yych <= 'N') {
		if (yych <= '-') {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy69;
				goto yy226;
			} else {
				if (yych == '"') goto yy228;
				goto yy69;
			}
		} else {
			if (yych <= '>') {
				if (yych <= '.') goto yy229;
				if (yych <= '=') goto yy69;
				goto yy239;
			} else {
				if (yych == 'D') goto yy240;
				goto yy69;
			}
		}
	} else {
		if (yych <= 'd') {
			if (yych <= 'R') {
				if (yych <= 'O') goto yy241;
				if (yych <= 'Q') goto yy69;
				goto yy242;
			} else {
				if (yych <= 'S') goto yy243;
				if (yych <= 'c') goto yy69;
				goto yy244;
			}
		} else {
			if (yych <= 'q') {
				if (yych == 'o') goto yy245;
				goto yy69;
			} else {
				if (yych <= 'r') goto yy246;
				if (yych <= 's') goto yy247;
				goto yy69;
			}
		}
	}
yy49:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 2) {
		goto yy230;
	}
	if (yych <= '!') {
		if (yych == ' ') goto yy226;
		goto yy69;
	} else {
		if (yych <= '"') goto yy228;
		if (yych == '.') goto yy229;
		goto yy69;
	}
yy50:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy214;
	if (yych == '"') goto yy216;
	goto yy69;
yy51:
	yych = *++YYCURSOR;
	if (yych == 'C') goto yy206;
	if (yych == 'I') goto yy207;
	goto yy69;
yy52:
	yych = *++YYCURSOR;
	if (yych == 'c') goto yy198;
	if (yych == 'i') goto yy199;
	goto yy69;
yy53:
	yych = *++YYCURSOR;
	if (yych == 'R') goto yy190;
	if (yych == 'V') goto yy191;
	goto yy69;
yy54:
	yych = *++YYCURSOR;
	if (yych == 'r') goto yy182;
	if (yych == 'v') goto yy183;
	goto yy69;
yy55:
	yych = *++YYCURSOR;
	if (yych <= '=') {
		if (yych <= '/') {
			if (yych == ' ') goto yy165;
			goto yy69;
		} else {
			if (yych <= '0') goto yy167;
			if (yych <= '<') goto yy69;
			goto yy168;
		}
	} else {
		if (yych <= 'R') {
			if (yych <= '>') goto yy169;
			if (yych <= 'Q') goto yy69;
			goto yy170;
		} else {
			if (yych == 'r') goto yy171;
			goto yy69;
		}
	}
yy56:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy163;
	goto yy69;
yy57:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy155;
	if (yych == '=') goto yy157;
	goto yy69;
yy58:
	yych = *++YYCURSOR;
	if (yych == 'B') goto yy147;
	if (yych == 'N') goto yy148;
	goto yy69;
yy59:
	yych = *++YYCURSOR;
	if (yych == 'b') goto yy139;
	if (yych == 'n') goto yy140;
	goto yy69;
yy60:
	yych = *++YYCURSOR;
	if (yych == 'O') goto yy135;
	goto yy69;
yy61:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy131;
	goto yy69;
yy62:
	yych = *++YYCURSOR;
	if (yych <= '0') {
		if (yych == ' ') goto yy120;
		if (yych <= '/') goto yy69;
		goto yy122;
	} else {
		if (yych <= ';') goto yy69;
		if (yych <= '<') goto yy123;
		if (yych <= '=') goto yy124;
		goto yy69;
	}
yy63:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy115;
	if (yych == '/') goto yy117;
	goto yy69;
yy64:
	yych = *++YYCURSOR;
	if (yych <= 'H') {
		if (yych == 'A') goto yy103;
		goto yy69;
	} else {
		if (yych <= 'I') goto yy104;
		if (yych == 'O') goto yy105;
		goto yy69;
	}
yy65:
	yych = *++YYCURSOR;
	if (yych <= 'h') {
		if (yych == 'a') goto yy91;
		goto yy69;
	} else {
		if (yych <= 'i') goto yy92;
		if (yych == 'o') goto yy93;
		goto yy69;
	}
yy66:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy86;
	if (yych == '0') goto yy88;
	goto yy69;
yy67:
	yych = *++YYCURSOR;
	if (yybm[256+yych] & 32) {
		goto yy75;
	}
	if (yych == ')') goto yy73;
	goto yy74;
yy68:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy69:
	if (yybm[256+yych] & 8) {
		goto yy68;
	}
	if (yych != ' ') goto yy2;
	++YYCURSOR;
yy71:
	{
                                                if(curr_state == WORD_DEF)
                                                {
                                                    // Are we adding a new word definition?
                                                    if(add_word == true)
                                                    {
                                                        add_word = false;
                                                        d_word_def(str_start, (str - 1));
                                                    }
                                                    else
                                                    {
                                                        if(compile_word(str_start, (str - 1)) < 0)
                                                            curr_state = ERROR_OCCURED;
                                                    }
                                                }
                                                else if(curr_state == IMPORT_LIBRARY)
                                                {
#if HAVE_FFI
                                                    /*
                                                        if there's an error importing the library
                                                        we keep the parser going normally by setting
                                                       state equal to IMPORT_FUNCTION but we set
                                                       the ffi_lib_state to NOT_OK_TO_IMPORT_FUNC
                                                    */
                                                    if(!ffi_import_lib(str_start, str - 1))
                                                    {
                                                        ffi_lib_state = NOT_OK_TO_IMPORT_FUNC;
                                                    }
                                                    else
                                                    {
                                                        ffi_lib_state = OK_TO_IMPORT_FUNC;
                                                    }
#else
                                                    printf("ERROR: FFI interface is not enabled in this build.\n");
                                                    compiler_error();
#endif
                                                    curr_state = IMPORT_FUNCTION;
                                                    break;
                                                }
                                                else if(curr_state == SAVE_TO_ARRAY)
                                                {
                                                    /* pass the PFE */
                                                    if(!d_compa(str_start, str - 1))
                                                        curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else if(curr_state == SAVE_TO_BIN_FILE)
                                                {
                                                    /* pass the PFE */
                                                    if(!d_compb(str_start, str - 1))
                                                        curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else if(curr_state == OPEN_BIN_FILE)
                                                {
                                                    if(!d_bin_file_run(str_start, str - 1))
                                                        curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else if(curr_state == OPEN_TXT_FILE)
                                                {
                                                    if(!d_include(str_start, str - 1))
                                                        curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else if(curr_state == INCLUDE_FILE)
                                                {
                                                    if(!d_include(str_start, str - 1))
                                                        curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else if(curr_state == VOC_DEF)
                                                {
                                                    if(!d_newvoc(str_start, (str - 1)))
                                                        curr_state = ERROR_OCCURED;
                                                }
                                                else if(curr_state == MACRO_DEF_NAME)
                                                {
                                                    if(d_macro_name(str_start, (str - 1)))
                                                        curr_state = MACRO_DEF_VAL;
                                                    else
                                                        curr_state = ERROR_OCCURED;
                                                }
                                                else if(curr_state == VAR_DEF_NAME)
                                                {
                                                    if(d_var_name(str_start, (str - 1)))
                                                        curr_state = VAR_DEF_VAL;
                                                    else
                                                        curr_state = ERROR_OCCURED;
                                                }
                                                else if(curr_state == WORD_REMOVE)
                                                {
                                                    d_remove_word(str_start, (str - 1));
                                                    curr_state = WORD_REMOVE_END;
                                                }
/*
                                                else if(curr_state == STRING_DEF)
                                                {
printf("-- %s\n", str_start);
                                                    if(utmp = d_str_def(str_start, (str - 1)))
                                                    {
                                                        compile_integer_str((int8_t*) &utmp);
                                                        curr_state = STRING_DEF_END;
                                                    }
                                                    else
                                                        curr_state = ERROR_OCCURED;
                                                }
*/
                                                else
                                                {
                                                    if(compile_word(str_start, str - 1) < 0)
                                                        curr_state = ERROR_OCCURED;
                                                }
                                                continue;
                                            }
yy72:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) goto yy71;
	if (yych <= '~') goto yy78;
	goto yy71;
yy73:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
yy74:
	if (yybm[256+yych] & 16) {
		goto yy73;
	}
	if (yych <= 0x1F) goto yy2;
	if (yych <= ' ') goto yy72;
	if (yych <= '[') goto yy83;
	if (yych <= '\\') goto yy77;
	goto yy2;
yy75:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yybm[256+yych] & 32) {
		goto yy75;
	}
	if (yych <= ')') {
		if (yych <= 0x1F) goto yy2;
		if (yych <= ' ') goto yy72;
		if (yych <= '(') goto yy73;
		goto yy83;
	} else {
		if (yych == '\\') goto yy77;
		if (yych <= '~') goto yy73;
		goto yy2;
	}
yy77:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy78:
	if (yybm[256+yych] & 64) {
		goto yy77;
	}
	if (yych != ')') goto yy2;
yy79:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[256+yych] & 128) {
		goto yy79;
	}
	if (yych <= 0x1F) goto yy2;
	if (yych <= ' ') goto yy81;
	if (yych <= '~') goto yy77;
	goto yy2;
yy81:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[256+yych] & 64) {
		goto yy77;
	}
	if (yych == ')') goto yy79;
yy82:
	{
                                                if(curr_state == WORD_DEF)
                                                {
                                                    add_worddef_cmt(str_start, (str -1));
                                                }
                                                continue;
                                            }
yy83:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yybm[256+yych] & 16) {
		goto yy73;
	}
	if (yych <= 0x1F) goto yy2;
	if (yych <= ' ') goto yy85;
	if (yych <= '[') goto yy83;
	if (yych <= '\\') goto yy77;
	goto yy2;
yy85:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) goto yy82;
	if (yych <= '~') goto yy78;
	goto yy82;
yy86:
	++YYCURSOR;
	{ add_byte(TOKEN_EQ); continue; }
yy88:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_EQ0); continue; }
yy91:
	yych = *++YYCURSOR;
	if (yych == 'x') goto yy100;
	goto yy69;
yy92:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy97;
	goto yy69;
yy93:
	yych = *++YYCURSOR;
	if (yych != 'd') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEM_MOD); continue; }
yy97:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_MIN); continue; }
yy100:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_MAX); continue; }
yy103:
	yych = *++YYCURSOR;
	if (yych == 'X') goto yy112;
	goto yy69;
yy104:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy109;
	goto yy69;
yy105:
	yych = *++YYCURSOR;
	if (yych != 'D') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEM_MOD); continue; }
yy109:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_MIN); continue; }
yy112:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_MAX); continue; }
yy115:
	++YYCURSOR;
	{ add_byte(TOKEN_MUL); continue; }
yy117:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_MULDIV); continue; }
yy120:
	++YYCURSOR;
	{ add_byte(TOKEN_LT); continue; }
yy122:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy129;
	goto yy69;
yy123:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy127;
	goto yy69;
yy124:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_LE); continue; }
yy127:
	++YYCURSOR;
	{ add_byte(TOKEN_LSHIFT); continue; }
yy129:
	++YYCURSOR;
	{ add_byte(TOKEN_LT0); continue; }
yy131:
	yych = *++YYCURSOR;
	if (yych != 'r') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_XOR); continue; }
yy135:
	yych = *++YYCURSOR;
	if (yych != 'R') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_XOR); continue; }
yy139:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy144;
	goto yy69;
yy140:
	yych = *++YYCURSOR;
	if (yych != 'd') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_AND); continue; }
yy144:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_ABS); continue; }
yy147:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy152;
	goto yy69;
yy148:
	yych = *++YYCURSOR;
	if (yych != 'D') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_AND); continue; }
yy152:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_ABS); continue; }
yy155:
	++YYCURSOR;
	{ add_byte(TOKEN_STORE); continue; }
yy157:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy158;
	if (yych == '0') goto yy160;
	goto yy69;
yy158:
	++YYCURSOR;
	{ add_byte(TOKEN_NEQ); continue; }
yy160:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NEQ0); continue; }
yy163:
	++YYCURSOR;
	{ add_byte(TOKEN_FETCH); continue; }
yy165:
	++YYCURSOR;
	{ add_byte(TOKEN_GT); continue; }
yy167:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy180;
	goto yy69;
yy168:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy178;
	goto yy69;
yy169:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy176;
	goto yy69;
yy170:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy174;
	goto yy69;
yy171:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TO_RSTACK); continue; }
yy174:
	++YYCURSOR;
	{ add_byte(TOKEN_TO_RSTACK); continue; }
yy176:
	++YYCURSOR;
	{ add_byte(TOKEN_RSHIFT); continue; }
yy178:
	++YYCURSOR;
	{ add_byte(TOKEN_GE); continue; }
yy180:
	++YYCURSOR;
	{ add_byte(TOKEN_GT0); continue; }
yy182:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy188;
	goto yy69;
yy183:
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'r') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_OVER); continue; }
yy188:
	++YYCURSOR;
	{ add_byte(TOKEN_OR); continue; }
yy190:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy196;
	goto yy69;
yy191:
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'R') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_OVER); continue; }
yy196:
	++YYCURSOR;
	{ add_byte(TOKEN_OR); continue; }
yy198:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy204;
	goto yy69;
yy199:
	yych = *++YYCURSOR;
	if (yych != 'c') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'k') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_PICK); continue; }
yy204:
	++YYCURSOR;
	{ add_byte(TOKEN_PC); continue; }
yy206:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy212;
	goto yy69;
yy207:
	yych = *++YYCURSOR;
	if (yych != 'C') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'K') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_PICK); continue; }
yy212:
	++YYCURSOR;
	{ add_byte(TOKEN_PC); continue; }
yy214:
	++YYCURSOR;
	{
#if HAVE_PRINTF
                                                add_byte(TOKEN_PRINT); continue;
#else
                                                printf("ERROR: printf is not enabled in this build.\n");
                                                compiler_error();
#endif
                                            }
yy216:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '.') {
		if (yych <= '&') {
			if (yych <= 0x1F) goto yy71;
			if (yych <= '!') goto yy218;
			if (yych <= '#') goto yy71;
		} else {
			if (yych <= '*') {
				if (yych <= ')') goto yy71;
			} else {
				if (yych <= ',') goto yy71;
				if (yych >= '.') goto yy220;
			}
		}
	} else {
		if (yych <= '^') {
			if (yych <= '?') {
				if (yych >= ';') goto yy71;
			} else {
				if (yych <= '[') goto yy218;
				if (yych <= ']') goto yy71;
			}
		} else {
			if (yych <= '{') {
				if (yych <= '_') goto yy71;
			} else {
				if (yych <= '|') goto yy71;
				if (yych >= 0x7F) goto yy71;
			}
		}
	}
yy218:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 1) {
		goto yy218;
	}
	if (yych == '"') goto yy224;
	goto yy2;
yy220:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 1) {
		goto yy218;
	}
	if (yych != '"') goto yy2;
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych != ' ') goto yy2;
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '.') {
		if (yych <= '&') {
			if (yych <= 0x1F) goto yy223;
			if (yych <= '!') goto yy218;
			if (yych >= '$') goto yy218;
		} else {
			if (yych <= '*') {
				if (yych >= '*') goto yy218;
			} else {
				if (yych <= ',') goto yy223;
				if (yych <= '-') goto yy218;
				goto yy220;
			}
		}
	} else {
		if (yych <= '^') {
			if (yych <= '?') {
				if (yych <= ':') goto yy218;
			} else {
				if (yych <= '[') goto yy218;
				if (yych >= '^') goto yy218;
			}
		} else {
			if (yych <= '{') {
				if (yych >= '`') goto yy218;
			} else {
				if (yych <= '|') goto yy223;
				if (yych <= '~') goto yy218;
			}
		}
	}
yy223:
	{
#if HAVE_PRINTF
                                                tmp = d_str_def(str_start, (str - 1));

                                                if(tmp != -1)
                                                {
                                                    compile_integer(tmp);
                                                    add_byte(TOKEN_PRINT_STR);
                                                }
                                                else
                                                {
                                                    curr_state = ERROR_OCCURED;
                                                }
                                                continue;
#else
                                                printf("ERROR: printf is not enabled in this build.\n");
                                                compiler_error();
#endif
                                            }
yy224:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy2;
	yych = *++YYCURSOR;
	goto yy223;
yy226:
	++YYCURSOR;
yy227:
	{
                                                            if(curr_state == MACRO_DEF_VAL)
                                                            {
                                                                if(d_macro_value(str_start, (str - 1), MACRO_VAL_TYPE_SC))
                                                                    curr_state = MACRO_DEF_END;
                                                                else
                                                                    curr_state = ERROR_OCCURED;
                                                                break;
                                                            }
                                                            else if(curr_state == VAR_DEF_VAL)
                                                            {
#if HAVE_FP_NUMBERS
                                                                if(add_var_val(str_start, (str - 1), VAR_VAL_TYPE_SC))
#else
                                                                if(add_var_val(str_start, (str - 1)))
#endif
                                                                    curr_state = VAR_DEF_END;
                                                                else
                                                                    curr_state = ERROR_OCCURED;
                                                                break;
                                                            }
                                                            else
                                                            {
                                                                if(!compile_integer_str(str_start, (str - 1)))
                                                                    curr_state = ERROR_OCCURED;
                                                            }
                                                            continue;
                                                        }
yy228:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) goto yy227;
	if (yych == '\\') goto yy227;
	if (yych <= '~') goto yy69;
	goto yy227;
yy229:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy69;
	if (yych <= '9') goto yy234;
	goto yy69;
yy230:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 2) {
		goto yy230;
	}
	if (yych <= '-') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy2;
		} else {
			if (yych == '"') goto yy233;
			goto yy68;
		}
	} else {
		if (yych <= '[') {
			if (yych <= '.') goto yy229;
			goto yy68;
		} else {
			if (yych <= '\\') goto yy2;
			if (yych <= '~') goto yy68;
			goto yy2;
		}
	}
yy232:
	yych = *++YYCURSOR;
	goto yy227;
yy233:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) goto yy227;
	if (yych == '\\') goto yy227;
	if (yych <= '~') goto yy69;
	goto yy227;
yy234:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yych <= '/') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy2;
		} else {
			if (yych == '"') goto yy238;
			goto yy68;
		}
	} else {
		if (yych <= '[') {
			if (yych <= '9') goto yy234;
			goto yy68;
		} else {
			if (yych <= '\\') goto yy2;
			if (yych <= '~') goto yy68;
			goto yy2;
		}
	}
	++YYCURSOR;
yy237:
	{
#if HAVE_FP_NUMBERS
                                                            if(curr_state == MACRO_DEF_VAL)
                                                            {
                                                                if(d_macro_value(str_start, (str - 1), MACRO_VAL_TYPE_FP))
                                                                    curr_state = MACRO_DEF_END;
                                                                else
                                                                    curr_state = ERROR_OCCURED;
                                                                break;
                                                            }
                                                            else if(curr_state == VAR_DEF_VAL)
                                                            {
                                                                if(add_var_val(str_start, (str - 1), VAR_VAL_TYPE_FP))
                                                                    curr_state = VAR_DEF_END;
                                                                else
                                                                    curr_state = ERROR_OCCURED;
                                                                break;
                                                            }
                                                            else
                                                            {
                                                                compile_fp_str(str_start, (str - 1));
                                                            }
                                                            continue;
#else
                                                            printf("ERROR: Floating point numbers are not enabled in this build.\n");
                                                            compiler_error();
                                                            curr_state = ERROR_OCCURED;
                                                            break;
#endif
                                                        }
yy238:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) goto yy237;
	if (yych == '\\') goto yy237;
	if (yych <= '~') goto yy69;
	goto yy237;
yy239:
	yych = *++YYCURSOR;
	if (yych == 'R') goto yy306;
	if (yych == 'r') goto yy307;
	goto yy69;
yy240:
	yych = *++YYCURSOR;
	if (yych == 'R') goto yy297;
	if (yych == 'U') goto yy298;
	goto yy69;
yy241:
	yych = *++YYCURSOR;
	if (yych == 'V') goto yy292;
	goto yy69;
yy242:
	yych = *++YYCURSOR;
	if (yych <= '?') {
		if (yych == '>') goto yy283;
		goto yy69;
	} else {
		if (yych <= '@') goto yy284;
		if (yych == 'O') goto yy282;
		goto yy69;
	}
yy243:
	yych = *++YYCURSOR;
	if (yych == 'W') goto yy277;
	goto yy69;
yy244:
	yych = *++YYCURSOR;
	if (yych == 'r') goto yy268;
	if (yych == 'u') goto yy269;
	goto yy69;
yy245:
	yych = *++YYCURSOR;
	if (yych == 'v') goto yy263;
	goto yy69;
yy246:
	yych = *++YYCURSOR;
	if (yych <= '?') {
		if (yych == '>') goto yy254;
		goto yy69;
	} else {
		if (yych <= '@') goto yy255;
		if (yych == 'o') goto yy253;
		goto yy69;
	}
yy247:
	yych = *++YYCURSOR;
	if (yych != 'w') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'a') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_SWAP); continue; }
yy253:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy260;
	goto yy69;
yy254:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy258;
	goto yy69;
yy255:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_FETCH_RSTACK); continue; }
yy258:
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_FROM_RSTACK); continue; }
yy260:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_ROT); continue; }
yy263:
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'r') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_OVER); continue; }
yy268:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy273;
	goto yy69;
yy269:
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_DUP); continue; }
yy273:
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_DROP); continue; }
yy277:
	yych = *++YYCURSOR;
	if (yych != 'A') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_SWAP); continue; }
yy282:
	yych = *++YYCURSOR;
	if (yych == 'T') goto yy289;
	goto yy69;
yy283:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy287;
	goto yy69;
yy284:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_FETCH_RSTACK); continue; }
yy287:
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_FROM_RSTACK); continue; }
yy289:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_ROT); continue; }
yy292:
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'R') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_OVER); continue; }
yy297:
	yych = *++YYCURSOR;
	if (yych == 'O') goto yy302;
	goto yy69;
yy298:
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_DUP); continue; }
yy302:
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_DROP); continue; }
yy306:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy310;
	goto yy69;
yy307:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_TO_RSTACK); continue; }
yy310:
	++YYCURSOR;
	{ add_byte(TOKEN_TWO_TO_RSTACK); continue; }
yy312:
	++YYCURSOR;
	{ add_byte(TOKEN_SUB); continue; }
yy314:
	++YYCURSOR;
	{ add_byte(TOKEN_ADD); continue; }
yy316:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '@') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy227;
			goto yy344;
		} else {
			if (yych == '"') goto yy344;
			goto yy227;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy342;
			if (yych <= '^') goto yy227;
			goto yy342;
		} else {
			if (yych <= '`') goto yy227;
			if (yych <= 'z') goto yy342;
			goto yy227;
		}
	}
yy317:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yybm[0+yych] & 8) {
		goto yy325;
	}
	if (yych <= '\\') {
		if (yych <= '@') {
			if (yych <= 0x1F) goto yy227;
			if (yych <= ' ') goto yy324;
			goto yy68;
		} else {
			if (yych <= 'Z') goto yy327;
			if (yych <= '[') goto yy68;
			goto yy227;
		}
	} else {
		if (yych <= '`') {
			if (yych == '_') goto yy327;
			goto yy68;
		} else {
			if (yych <= 'z') goto yy327;
			if (yych <= '~') goto yy68;
			goto yy227;
		}
	}
yy318:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy348;
	goto yy69;
yy319:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy346;
	goto yy69;
yy320:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 4) {
		goto yy320;
	}
	if (yych <= '.') {
		if (yych <= '!') {
			if (yych <= 0x1F) goto yy2;
			if (yych >= '!') goto yy68;
		} else {
			if (yych <= '"') goto yy323;
			if (yych <= '-') goto yy68;
			goto yy229;
		}
	} else {
		if (yych <= '[') {
			if (yych <= '/') goto yy68;
			if (yych <= '9') goto yy230;
			goto yy68;
		} else {
			if (yych <= '\\') goto yy2;
			if (yych <= '~') goto yy68;
			goto yy2;
		}
	}
yy322:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '@') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy227;
			goto yy344;
		} else {
			if (yych == '"') goto yy344;
			goto yy227;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy342;
			if (yych <= '^') goto yy227;
			goto yy342;
		} else {
			if (yych <= '`') goto yy227;
			if (yych <= 'z') goto yy342;
			goto yy227;
		}
	}
yy323:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yybm[0+yych] & 8) {
		goto yy325;
	}
	if (yych <= '\\') {
		if (yych <= '@') {
			if (yych <= 0x1F) goto yy227;
			if (yych >= '!') goto yy68;
		} else {
			if (yych <= 'Z') goto yy327;
			if (yych <= '[') goto yy68;
			goto yy227;
		}
	} else {
		if (yych <= '`') {
			if (yych == '_') goto yy327;
			goto yy68;
		} else {
			if (yych <= 'z') goto yy327;
			if (yych <= '~') goto yy68;
			goto yy227;
		}
	}
yy324:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= '@') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy71;
			goto yy344;
		} else {
			if (yych == '"') goto yy344;
			goto yy71;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy342;
			if (yych <= '^') goto yy71;
			goto yy342;
		} else {
			if (yych <= '`') goto yy71;
			if (yych <= 'z') goto yy342;
			goto yy71;
		}
	}
yy325:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 8) {
		goto yy325;
	}
	if (yych <= '\\') {
		if (yych <= '@') {
			if (yych <= 0x1F) goto yy2;
			if (yych <= ' ') goto yy324;
			goto yy68;
		} else {
			if (yych <= 'Z') goto yy327;
			if (yych <= '[') goto yy68;
			goto yy2;
		}
	} else {
		if (yych <= '`') {
			if (yych != '_') goto yy68;
		} else {
			if (yych <= 'z') goto yy327;
			if (yych <= '~') goto yy68;
			goto yy2;
		}
	}
yy327:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 16) {
		goto yy327;
	}
	if (yych <= '"') {
		if (yych <= 0x1F) goto yy2;
		if (yych <= ' ') goto yy329;
		if (yych <= '!') goto yy68;
		goto yy330;
	} else {
		if (yych == '\\') goto yy2;
		if (yych <= '~') goto yy68;
		goto yy2;
	}
yy329:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yybm[0+yych] & 32) {
		goto yy339;
	}
	if (yych <= '/') goto yy71;
	if (yych <= '9') goto yy337;
	goto yy71;
yy330:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yych <= '/') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy2;
			goto yy329;
		} else {
			if (yych == '"') goto yy330;
			goto yy68;
		}
	} else {
		if (yych <= '[') {
			if (yych >= ':') goto yy68;
		} else {
			if (yych <= '\\') goto yy2;
			if (yych <= '~') goto yy68;
			goto yy2;
		}
	}
yy332:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yych <= '/') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy2;
		} else {
			if (yych == '"') goto yy336;
			goto yy68;
		}
	} else {
		if (yych <= '[') {
			if (yych <= '9') goto yy332;
			goto yy68;
		} else {
			if (yych <= '\\') goto yy2;
			if (yych <= '~') goto yy68;
			goto yy2;
		}
	}
	++YYCURSOR;
yy335:
	{
                                                        if(curr_state == IMPORT_FUNCTION)
                                                        {
#if HAVE_FFI
                                                            if(ffi_lib_state == OK_TO_IMPORT_FUNC)
                                                            {
                                                                if(!ffi_import_func(str_start, str - 1))
                                                                {
                                                                    curr_state = ERROR_OCCURED;
                                                                }
                                                            }
#else
                                                            curr_state = ERROR_OCCURED;
#endif
                                                            break;
                                                        }

                                                    }
yy336:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) goto yy335;
	if (yych == '\\') goto yy335;
	if (yych <= '~') goto yy69;
	goto yy335;
yy337:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '!') {
		if (yych == ' ') goto yy341;
		goto yy2;
	} else {
		if (yych <= '"') goto yy341;
		if (yych <= '/') goto yy2;
		if (yych <= '9') goto yy337;
		goto yy2;
	}
yy339:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 32) {
		goto yy339;
	}
	if (yych <= '/') goto yy2;
	if (yych <= '9') goto yy337;
	goto yy2;
yy341:
	yych = *++YYCURSOR;
	goto yy335;
yy342:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 32) {
		goto yy339;
	}
	if (yych <= '^') {
		if (yych <= '@') goto yy2;
		if (yych <= 'Z') goto yy342;
		goto yy2;
	} else {
		if (yych == '`') goto yy2;
		if (yych <= 'z') goto yy342;
		goto yy2;
	}
yy344:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= '@') {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy2;
			goto yy344;
		} else {
			if (yych == '"') goto yy344;
			goto yy2;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy342;
			if (yych <= '^') goto yy2;
			goto yy342;
		} else {
			if (yych <= '`') goto yy2;
			if (yych <= 'z') goto yy342;
			goto yy2;
		}
	}
yy346:
	++YYCURSOR;
	{ add_byte(TOKEN_DEC); continue; }
yy348:
	++YYCURSOR;
	{ add_byte(TOKEN_INC); continue; }
yy350:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if (yych <= '/') {
		if (yych <= '!') {
			if (yych <= 0x1F) goto yy2;
			if (yych <= ' ') goto yy322;
			goto yy68;
		} else {
			if (yych <= '"') goto yy323;
			if (yych == '.') goto yy229;
			goto yy68;
		}
	} else {
		if (yych <= '9') {
			if (yych <= '1') goto yy350;
			if (yych >= '8') goto yy230;
		} else {
			if (yych == '\\') goto yy2;
			if (yych <= '~') goto yy68;
			goto yy2;
		}
	}
yy352:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 64) {
		goto yy352;
	}
	if (yych <= '.') {
		if (yych <= '!') {
			if (yych <= 0x1F) goto yy2;
			if (yych <= ' ') goto yy232;
			goto yy68;
		} else {
			if (yych <= '"') goto yy233;
			if (yych <= '-') goto yy68;
			goto yy229;
		}
	} else {
		if (yych <= '[') {
			if (yych <= '/') goto yy68;
			if (yych <= '9') goto yy230;
			goto yy68;
		} else {
			if (yych <= '\\') goto yy2;
			if (yych <= '~') goto yy68;
			goto yy2;
		}
	}
yy354:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy355;
	}
	goto yy69;
yy355:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy355;
	}
	if (yych <= '"') {
		if (yych <= 0x1F) goto yy2;
		if (yych <= ' ') goto yy226;
		if (yych <= '!') goto yy68;
		goto yy228;
	} else {
		if (yych == '\\') goto yy2;
		if (yych <= '~') goto yy68;
		goto yy2;
	}
yy357:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy379;
	goto yy69;
yy358:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy365;
	if (yych == 'e') goto yy364;
	goto yy69;
yy359:
	yych = *++YYCURSOR;
	if (yych != 'a') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_SWAP); continue; }
yy364:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy376;
	goto yy69;
yy365:
	yych = *++YYCURSOR;
	if (yych != 'c') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'k') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'o') goto yy69;
	yych = *++YYCURSOR;
	if (yych == 'f') goto yy370;
	if (yych != 'n') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy374;
	goto yy69;
yy370:
	yych = *++YYCURSOR;
	if (yych != 'f') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_showstackoff(); continue; }
yy374:
	++YYCURSOR;
	{ d_showstackon(); continue; }
yy376:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_step(); continue; }
yy379:
	++YYCURSOR;
	{ add_byte(TOKEN_SP); continue; }
yy381:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy403;
	goto yy69;
yy382:
	yych = *++YYCURSOR;
	if (yych == 'A') goto yy389;
	if (yych == 'E') goto yy388;
	goto yy69;
yy383:
	yych = *++YYCURSOR;
	if (yych != 'A') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_SWAP); continue; }
yy388:
	yych = *++YYCURSOR;
	if (yych == 'P') goto yy400;
	goto yy69;
yy389:
	yych = *++YYCURSOR;
	if (yych != 'C') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'K') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'O') goto yy69;
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy394;
	if (yych != 'N') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy398;
	goto yy69;
yy394:
	yych = *++YYCURSOR;
	if (yych != 'F') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_showstackoff(); continue; }
yy398:
	++YYCURSOR;
	{ d_showstackon(); continue; }
yy400:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_step(); continue; }
yy403:
	++YYCURSOR;
	{ add_byte(TOKEN_SP); continue; }
yy405:
	yych = *++YYCURSOR;
	if (yych == 'g') goto yy431;
	goto yy69;
yy406:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy428;
	goto yy69;
yy407:
	yych = *++YYCURSOR;
	if (yych <= 'o') {
		if (yych == 'd') goto yy408;
		if (yych <= 'n') goto yy69;
		goto yy410;
	} else {
		if (yych <= 'r') goto yy69;
		if (yych <= 's') goto yy409;
		if (yych <= 't') goto yy411;
		goto yy69;
	}
yy408:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy422;
	goto yy69;
yy409:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy417;
	goto yy69;
yy410:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy414;
	goto yy69;
yy411:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NOT); continue; }
yy414:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NOOP); continue; }
yy417:
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_nostep(); continue; }
yy422:
	yych = *++YYCURSOR;
	if (yych != 'b') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'u') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'g') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_nodebug(); continue; }
yy428:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NIP); continue; }
yy431:
	yych = *++YYCURSOR;
	if (yych != 'a') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 't') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NEGATE); continue; }
yy437:
	yych = *++YYCURSOR;
	if (yych == 'G') goto yy463;
	goto yy69;
yy438:
	yych = *++YYCURSOR;
	if (yych == 'P') goto yy460;
	goto yy69;
yy439:
	yych = *++YYCURSOR;
	if (yych <= 'O') {
		if (yych == 'D') goto yy440;
		if (yych <= 'N') goto yy69;
		goto yy442;
	} else {
		if (yych <= 'R') goto yy69;
		if (yych <= 'S') goto yy441;
		if (yych <= 'T') goto yy443;
		goto yy69;
	}
yy440:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy454;
	goto yy69;
yy441:
	yych = *++YYCURSOR;
	if (yych == 'T') goto yy449;
	goto yy69;
yy442:
	yych = *++YYCURSOR;
	if (yych == 'P') goto yy446;
	goto yy69;
yy443:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NOT); continue; }
yy446:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NOOP); continue; }
yy449:
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_nostep(); continue; }
yy454:
	yych = *++YYCURSOR;
	if (yych != 'B') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'U') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'G') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_nodebug(); continue; }
yy460:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NIP); continue; }
yy463:
	yych = *++YYCURSOR;
	if (yych != 'A') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'T') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_NEGATE); continue; }
yy469:
	yych = *++YYCURSOR;
	if (yych != 'm') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych <= '`') goto yy69;
	if (yych <= 'a') goto yy472;
	if (yych <= 'b') goto yy473;
	goto yy69;
yy472:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy476;
	goto yy69;
yy473:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = SAVE_TO_BIN_FILE; continue; }
yy476:
	++YYCURSOR;
	{ curr_state = SAVE_TO_ARRAY; continue; }
yy478:
	yych = *++YYCURSOR;
	if (yych != 'M') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych <= '@') goto yy69;
	if (yych <= 'A') goto yy481;
	if (yych <= 'B') goto yy482;
	goto yy69;
yy481:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy485;
	goto yy69;
yy482:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = SAVE_TO_BIN_FILE; continue; }
yy485:
	++YYCURSOR;
	{ curr_state = SAVE_TO_ARRAY; continue; }
yy487:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy514;
	goto yy69;
yy488:
	yych = *++YYCURSOR;
	if (yych == 'N') goto yy506;
	goto yy69;
yy489:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy499;
	goto yy69;
yy490:
	yych = *++YYCURSOR;
	if (yych != 'n') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'c') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'l') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'u') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'd') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = INCLUDE_FILE; continue; }
yy499:
	yych = *++YYCURSOR;
	if (yych != 'f') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'i') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'n') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = MACRO_DEF_NAME; continue; }
yy506:
	yych = *++YYCURSOR;
	if (yych != 'C') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'L') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'U') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'D') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = INCLUDE_FILE; continue; }
yy514:
	yych = *++YYCURSOR;
	if (yych != 'F') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'I') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'N') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = MACRO_DEF_NAME; continue; }
yy521:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy549;
	if (yych == '/') goto yy551;
	goto yy69;
yy522:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy547;
	goto yy69;
yy523:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy545;
	goto yy69;
yy524:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy543;
	goto yy69;
yy525:
	yych = *++YYCURSOR;
	if (yych == '+') goto yy540;
	goto yy69;
yy526:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy533;
	goto yy69;
yy527:
	yych = *++YYCURSOR;
	if (yych != 'u') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 's') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'h') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_FLUSH); continue; }
yy533:
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy535;
	if (yych == 'b') goto yy537;
	goto yy69;
yy535:
	++YYCURSOR;
	{ curr_state = OPEN_TXT_FILE; continue; }
yy537:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = OPEN_BIN_FILE; continue; }
yy540:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FINC); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy543:
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FDIV); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy545:
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FSUB); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy547:
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FADD); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy549:
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FMUL); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy551:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FMULDIV); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy554:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy582;
	if (yych == '/') goto yy584;
	goto yy69;
yy555:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy580;
	goto yy69;
yy556:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy578;
	goto yy69;
yy557:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy576;
	goto yy69;
yy558:
	yych = *++YYCURSOR;
	if (yych == '+') goto yy573;
	goto yy69;
yy559:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy566;
	goto yy69;
yy560:
	yych = *++YYCURSOR;
	if (yych != 'U') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'S') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'H') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_FLUSH); continue; }
yy566:
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy568;
	if (yych == 'B') goto yy570;
	goto yy69;
yy568:
	++YYCURSOR;
	{ curr_state = OPEN_TXT_FILE; continue; }
yy570:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = OPEN_BIN_FILE; continue; }
yy573:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FINC); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy576:
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FDIV); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy578:
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FSUB); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy580:
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FADD); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy582:
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FMUL); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy584:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{
#if HAVE_FP_NUMBERS
                                                add_byte(TOKEN_FMULDIV); continue;
#else
                                                printf("ERROR: Floating point operations are not enabled in this build.\n");
                                                compiler_error();
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy587:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy617;
	goto yy69;
yy588:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy615;
	goto yy69;
yy589:
	yych = *++YYCURSOR;
	if (yych <= 'l') {
		if (yych == 'c') goto yy599;
		goto yy69;
	} else {
		if (yych <= 'm') goto yy597;
		if (yych == 's') goto yy598;
		goto yy69;
	}
yy590:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy594;
	goto yy69;
yy591:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_RP); continue; }
yy594:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_ROT); continue; }
yy597:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy610;
	goto yy69;
yy598:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy606;
	goto yy69;
yy599:
	yych = *++YYCURSOR;
	if (yych != 'u') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'r') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 's') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{
                                                if(curr_state != WORD_DEF)
                                                {
                                                    printf("ERROR: RECURSE is only valid within a word definition.\n");
                                                    compiler_error();
                                                    curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else if(g_current_word_def_addr == -1)
                                                {
                                                    printf("ERROR: No current valid word definition.\n");
                                                    compiler_error();
                                                    curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else
                                                {
                                                    d_recurse();
                                                    continue;
                                                }
                                            }
yy606:
	yych = *++YYCURSOR;
	if (yych != 't') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_reset(); continue; }
yy610:
	yych = *++YYCURSOR;
	if (yych != 'v') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = WORD_REMOVE; continue; }
yy615:
	++YYCURSOR;
	{ add_byte(TOKEN_FETCH_RSTACK); continue; }
yy617:
	++YYCURSOR;
	{ add_byte(TOKEN_FROM_RSTACK); continue; }
yy619:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy649;
	goto yy69;
yy620:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy647;
	goto yy69;
yy621:
	yych = *++YYCURSOR;
	if (yych <= 'L') {
		if (yych == 'C') goto yy631;
		goto yy69;
	} else {
		if (yych <= 'M') goto yy629;
		if (yych == 'S') goto yy630;
		goto yy69;
	}
yy622:
	yych = *++YYCURSOR;
	if (yych == 'T') goto yy626;
	goto yy69;
yy623:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_RP); continue; }
yy626:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_ROT); continue; }
yy629:
	yych = *++YYCURSOR;
	if (yych == 'O') goto yy642;
	goto yy69;
yy630:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy638;
	goto yy69;
yy631:
	yych = *++YYCURSOR;
	if (yych != 'U') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'R') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'S') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{
                                                if(curr_state != WORD_DEF)
                                                {
                                                    printf("ERROR: RECURSE is only valid within a word definition.\n");
                                                    compiler_error();
                                                    curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else if(g_current_word_def_addr == -1)
                                                {
                                                    printf("ERROR: No current valid word definition.\n");
                                                    compiler_error();
                                                    curr_state = ERROR_OCCURED;
                                                    break;
                                                }
                                                else
                                                {
                                                    d_recurse();
                                                    continue;
                                                }
                                            }
yy638:
	yych = *++YYCURSOR;
	if (yych != 'T') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_reset(); continue; }
yy642:
	yych = *++YYCURSOR;
	if (yych != 'V') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = WORD_REMOVE; continue; }
yy647:
	++YYCURSOR;
	{ add_byte(TOKEN_FETCH_RSTACK); continue; }
yy649:
	++YYCURSOR;
	{ add_byte(TOKEN_FROM_RSTACK); continue; }
yy651:
	yych = *++YYCURSOR;
	if (yych != 'r') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'i') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'a') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'b') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'l') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy659;
	if (yych != 's') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy661;
	goto yy69;
yy659:
	++YYCURSOR;
	{ curr_state = VAR_DEF_NAME; continue; }
yy661:
	++YYCURSOR;
	{ d_variables(); continue; }
yy663:
	yych = *++YYCURSOR;
	if (yych != 'R') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'I') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'A') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'B') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'L') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy671;
	if (yych != 'S') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy673;
	goto yy69;
yy671:
	++YYCURSOR;
	{ curr_state = VAR_DEF_NAME; continue; }
yy673:
	++YYCURSOR;
	{ d_variables(); continue; }
yy675:
	yych = *++YYCURSOR;
	if (yych != 'r') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'd') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 's') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_words(); continue; }
yy681:
	yych = *++YYCURSOR;
	if (yych != 'R') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'D') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'S') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_words(); continue; }
yy687:
	++YYCURSOR;
	{ curr_state = OK_TO_COMPILE; add_word = false; d_word_def_end(); continue; }
yy689:
	++YYCURSOR;
	{ curr_state = WORD_DEF; add_word = true; continue; }
yy691:
	++YYCURSOR;
	{ d_j(); continue; }
yy693:
	++YYCURSOR;
	{ d_j(); continue; }
yy695:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy704;
	goto yy69;
yy696:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy702;
	goto yy69;
yy697:
	yych = *++YYCURSOR;
	if (yych != 'o') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_loop(); continue; }
yy702:
	++YYCURSOR;
	{
#if HAVE_PRINTF
                                                add_byte(TOKEN_PRINT_LINEFEED); continue;
#else
                                                printf("ERROR: printf is not enabled in this build.\n");
                                                compiler_error();
#endif
                                            }
yy704:
	yych = *++YYCURSOR;
	if (yych != 'v') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_leave(); continue; }
yy709:
	yych = *++YYCURSOR;
	if (yych == 'A') goto yy718;
	goto yy69;
yy710:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy716;
	goto yy69;
yy711:
	yych = *++YYCURSOR;
	if (yych != 'O') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_loop(); continue; }
yy716:
	++YYCURSOR;
	{
#if HAVE_PRINTF
                                                add_byte(TOKEN_PRINT_LINEFEED); continue;
#else
                                                printf("ERROR: printf is not enabled in this build.\n");
                                                compiler_error();
#endif
                                            }
yy718:
	yych = *++YYCURSOR;
	if (yych != 'V') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_leave(); continue; }
yy723:
	yych = *++YYCURSOR;
	if (yych <= 'c') {
		if (yych <= 'a') goto yy69;
		if (yych <= 'b') goto yy737;
		goto yy738;
	} else {
		if (yych == 'f') goto yy736;
		goto yy69;
	}
yy724:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy734;
	goto yy69;
yy725:
	yych = *++YYCURSOR;
	if (yych == 'o') goto yy730;
	goto yy69;
yy726:
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_DUP); continue; }
yy730:
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_DROP); continue; }
yy734:
	++YYCURSOR;
	{ printf("\nxxx\n"); d_do(); continue; }
yy736:
	yych = *++YYCURSOR;
	if (yych == 'i') goto yy745;
	goto yy69;
yy737:
	yych = *++YYCURSOR;
	if (yych == 'u') goto yy741;
	goto yy69;
yy738:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_decimal(); continue; }
yy741:
	yych = *++YYCURSOR;
	if (yych != 'g') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_debug(); continue; }
yy745:
	yych = *++YYCURSOR;
	if (yych != 'n') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = MACRO_DEF_NAME; continue; }
yy750:
	yych = *++YYCURSOR;
	if (yych <= 'C') {
		if (yych <= 'A') goto yy69;
		if (yych <= 'B') goto yy764;
		goto yy765;
	} else {
		if (yych == 'F') goto yy763;
		goto yy69;
	}
yy751:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy761;
	goto yy69;
yy752:
	yych = *++YYCURSOR;
	if (yych == 'O') goto yy757;
	goto yy69;
yy753:
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_DUP); continue; }
yy757:
	yych = *++YYCURSOR;
	if (yych != 'P') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_DROP); continue; }
yy761:
	++YYCURSOR;
	{ d_do(); continue; }
yy763:
	yych = *++YYCURSOR;
	if (yych == 'I') goto yy772;
	goto yy69;
yy764:
	yych = *++YYCURSOR;
	if (yych == 'U') goto yy768;
	goto yy69;
yy765:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_decimal(); continue; }
yy768:
	yych = *++YYCURSOR;
	if (yych != 'G') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_debug(); continue; }
yy772:
	yych = *++YYCURSOR;
	if (yych != 'N') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = MACRO_DEF_NAME; continue; }
yy777:
	yych = *++YYCURSOR;
	if (yych != 't') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'i') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'l') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_until(); continue; }
yy783:
	yych = *++YYCURSOR;
	if (yych != 'T') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'I') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'L') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_until(); continue; }
yy789:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy800;
	goto yy69;
yy790:
	yych = *++YYCURSOR;
	if (yych == 'g') goto yy795;
	goto yy69;
yy791:
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = BYE; break; }
yy795:
	yych = *++YYCURSOR;
	if (yych != 'i') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'n') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_begin(); continue; }
yy800:
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_base(); continue; }
yy804:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy815;
	goto yy69;
yy805:
	yych = *++YYCURSOR;
	if (yych == 'G') goto yy810;
	goto yy69;
yy806:
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = BYE; break; }
yy810:
	yych = *++YYCURSOR;
	if (yych != 'I') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'N') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_begin(); continue; }
yy815:
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_base(); continue; }
yy819:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy825;
	goto yy69;
yy820:
	yych = *++YYCURSOR;
	if (yych != 'c') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'k') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TUCK); continue; }
yy825:
	yych = *++YYCURSOR;
	if (yych != 'n') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_then(); continue; }
yy829:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy835;
	goto yy69;
yy830:
	yych = *++YYCURSOR;
	if (yych != 'C') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'K') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_TUCK); continue; }
yy835:
	yych = *++YYCURSOR;
	if (yych != 'N') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_then(); continue; }
yy839:
	yych = *++YYCURSOR;
	if (yych != 's') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_else(); continue; }
yy844:
	yych = *++YYCURSOR;
	if (yych != 'S') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_else(); continue; }
yy849:
	++YYCURSOR;
	{ d_i(); continue; }
yy851:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy872;
	goto yy69;
yy852:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy861;
	goto yy69;
yy853:
	yych = *++YYCURSOR;
	if (yych != 'c') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'l') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'u') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'd') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = INCLUDE_FILE; continue; }
yy861:
	yych = *++YYCURSOR;
	if (yych != 'o') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'r') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 't') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy865;
	if (yych == 'e') goto yy867;
	goto yy69;
yy865:
	++YYCURSOR;
	{
#if HAVE_FFI
                                                curr_state = IMPORT_LIBRARY; ffi_lib_state = NOT_OK_TO_IMPORT_FUNC; continue;
#else
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy867:
	yych = *++YYCURSOR;
	if (yych != 'n') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'd') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{
#if HAVE_FFI
                                                if(curr_state == IMPORT_FUNCTION)
                                                {
                                                    if(ffi_lib_state == OK_TO_IMPORT_FUNC)
                                                    {
                                                        ffi_import_end();
                                                    }

                                                    curr_state = IMPORT_END;
                                                }
                                                else
                                                {
                                                    curr_state = ERROR_OCCURED;
                                                    printf("ERROR: import_end identifier without an import.\n");
                                                    compiler_error();
                                                }
#else
                                                curr_state = ERROR_OCCURED;
#endif
                                                break;
                                            }
yy872:
	++YYCURSOR;
	{ d_if(); continue; }
yy874:
	++YYCURSOR;
	{ d_i(); continue; }
yy876:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy897;
	goto yy69;
yy877:
	yych = *++YYCURSOR;
	if (yych == 'P') goto yy886;
	goto yy69;
yy878:
	yych = *++YYCURSOR;
	if (yych != 'C') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'L') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'U') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'D') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'E') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = INCLUDE_FILE; continue; }
yy886:
	yych = *++YYCURSOR;
	if (yych != 'O') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'R') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'T') goto yy69;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy890;
	if (yych == 'E') goto yy892;
	goto yy69;
yy890:
	++YYCURSOR;
	{
#if HAVE_FFI
                                                curr_state = IMPORT_LIBRARY; ffi_lib_state = NOT_OK_TO_IMPORT_FUNC; continue;
#else
                                                curr_state = ERROR_OCCURED;
#endif
                                            }
yy892:
	yych = *++YYCURSOR;
	if (yych != 'N') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'D') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{
#if HAVE_FFI
                                                if(curr_state == IMPORT_FUNCTION)
                                                {

                                                    if(ffi_lib_state == OK_TO_IMPORT_FUNC)
                                                    {
                                                        ffi_import_end();
                                                    }

                                                    curr_state = IMPORT_END;
                                                }
                                                else
                                                {
                                                    curr_state = ERROR_OCCURED;
                                                    printf("ERROR: IMPORT_END identifier without an IMPORT.\n");
                                                    compiler_error();
                                                }
#else
                                                curr_state = ERROR_OCCURED;
#endif
                                                break;
                                            }
yy897:
	++YYCURSOR;
	{ d_if(); continue; }
yy899:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy900;
	if (yych == 'x') goto yy901;
	goto yy69;
yy900:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy904;
	goto yy69;
yy901:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_hex(); continue; }
yy904:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy905;
	if (yych == 'a') goto yy907;
	goto yy69;
yy905:
	++YYCURSOR;
	{ curr_state = WORD_HELP; d_help(str); break; }
yy907:
	yych = *++YYCURSOR;
	if (yych != 'l') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'l') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = PRINTED_HELP; d_helpall(); break; }
yy912:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy913;
	if (yych == 'X') goto yy914;
	goto yy69;
yy913:
	yych = *++YYCURSOR;
	if (yych == 'P') goto yy917;
	goto yy69;
yy914:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ d_hex(); continue; }
yy917:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy918;
	if (yych == 'A') goto yy920;
	goto yy69;
yy918:
	++YYCURSOR;
	{ curr_state = WORD_HELP; d_help(str); break; }
yy920:
	yych = *++YYCURSOR;
	if (yych != 'L') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'L') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ curr_state = PRINTED_HELP; d_helpall(); break; }
yy925:
	++YYCURSOR;
	{ prev_state = curr_state; curr_state = LINE_CMT; goto forth_line_comment; }
yy927:
	++YYCURSOR;
	{ add_byte(TOKEN_DIV); continue; }
yy929:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy942;
	goto yy69;
yy930:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) goto yy931;
	if (yych == '\\') goto yy931;
	if (yych <= '~') goto yy69;
yy931:
	{ prev_state = curr_state; curr_state = LINE_CMT; goto cpp_line_comment; }
yy932:
	yych = *++YYCURSOR;
	if (yych == 'O') goto yy938;
	goto yy69;
yy933:
	yych = *++YYCURSOR;
	if (yych != 'o') goto yy69;
	yych = *++YYCURSOR;
	if (yych != 'd') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_DIVMOD); continue; }
yy938:
	yych = *++YYCURSOR;
	if (yych != 'D') goto yy69;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy69;
	++YYCURSOR;
	{ add_byte(TOKEN_DIVMOD); continue; }
yy942:
	++YYCURSOR;
	{ prev_state = curr_state; curr_state = BLK_CMT; goto c_blk_comment; }
}


c_blk_comment:

        /*
            Skip everything between the start and end of the C comment. The end
            of the C comment serves as a termination boundary. Process any new
            lines the same as is done above.
         */


{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	if (yych == '\n') goto yy948;
	if (yych != '*') goto yy950;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == '/') goto yy951;
yy947:
	{ goto c_blk_comment; }
yy948:
	++YYCURSOR;
	{ break; }
yy950:
	yych = *++YYCURSOR;
	goto yy947;
yy951:
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy953;
	YYCURSOR = YYMARKER;
	goto yy947;
yy953:
	++YYCURSOR;
	{ curr_state = prev_state; continue; }
}


cpp_line_comment:

        /*
            Skip everything after the start of the CPP comment but before a new
            line. The new ine serves as a termination boundary. Process the new
            line the same as is done above.
         */


{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych != '\n') goto yy959;
	++YYCURSOR;
	{ curr_state = prev_state; break; }
yy959:
	++YYCURSOR;
	{ goto cpp_line_comment; }
}


forth_line_comment:

        /*
            Skip everything after the start of the Forth line comment but before
            a new line. The new ine serves as a termination boundary. Process the
            new line the same as is done above.
         */


{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych != '\n') goto yy965;
	++YYCURSOR;
	{ curr_state = prev_state; break; }
yy965:
	++YYCURSOR;
	{ goto forth_line_comment; }
}


    } /* for(;;) */

    return curr_state;
}

/* end of file */

